baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Infinite Pixels'

enableEmoji = true

[params]

relativeURLs = false

publishDir = "public/"

disableKinds = ["taxonomy", "term", "RSS", "section"]
ignoreErrors = ["error-disable-taxonomy", "error-no-layout"]

[taxonomies]

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.js"
    target = "assets/js/bootstrap.bundle.js"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/css/fonts"
  [[module.mounts]]
    source = "../infinite-engine/Export/html5/bin/InfiniteEngine.js"
    target = "assets/js/InfiniteEngine.js"
